### ISSUE TITLE
update openSSL version

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/Externals#10]
Backport to v6r3\* branch if what is in v6r4\* works as expected.

**Comment by petricm** [comment]
Hi,
also the defaults have to be updated.

- Disable weak ciphers offered by this service:
  SSL3_RSA_RC4_128_MD5
  SSL3_RSA_RC4_128_SHA
  SSL3_RSA_WITH_SEED_SHA
  TLS1_RSA_RC4_128_MD5
  TLS1_RSA_RC4_128_SHA

- Disable deprecated SSLv2 and SSLv3 and use instead TLSv1+

**Comment by petricm** [comment]
I would suggest to change 
osslConfArgs = "threads shared"
to
osslConfArgs = "threads shared no-ssl2 no-ssl3"

**Comment by atsareg** [comment]
Are you sure that at some very old worker nodes this will not make harm ?

**Comment by fstagni** [comment]
Just to be sure: is it a valid issue, even after using nginx on web portal?

**Comment by petricm** [comment]
Well the webportal is easily fixed with nginx and there are no problems. 
But you can still connect to the normal nodes via SSLv3 a on port 9131, which I don't think should be allowed.

**Comment by zmathe** [comment]
We have only one problem which is openSSL version. What I can say we are using TLSV1 protocol by default the others are disabled. If we want to connect to the machine and execute the handshake we have to use TLSV1 protocol. I have checked and we also using the correct CHIPERS. Everything is coded in DIRAC (CHIPERS and the protocol). We are not using the defaults provided by openssl. We are using exactly the same configuration what Nginx is using. This is DIRAC v6r15 I have not checked the oldest versions....

**Comment by fstagni** [comment]
Trying in https://github.com/DIRACGrid/Externals/pull/27
