### ISSUE TITLE
Ubuntu 16.04 installation error

### ISSUE THREAD

**Issue by vin-c** [DIRACGrid/Externals#21]
Hi there,

Could not download the compiled binary (file not found):
dirac-install [ERROR] http://lhcbproject.web.cern.ch/lhcbproject/dist/Dirac_project/installSource/Externals-client-v6r4p1-Linux_x86_64_glibc-2.23-python27.tar.gz does not exist

**Comment by vin-c** [comment]
Hi, tried this morning with an Ubuntu 14.04 VM...

dirac-install [ERROR] http://lhcbproject.web.cern.ch/lhcbproject/dist/Dirac_project/installSource/../lcgBundles/DIRAC-lcg-2015-07-09-Linux_x86_64_glibc-2.18-python27.tar.gz does not exist

**Comment by fstagni** [comment]
Ubuntu is not supported. And, very sorry for completely forgetting about this issue.
