### ISSUE TITLE
ARC libraries

### ISSUE THREAD

**Issue by rajanandakumar** [DIRACGrid/Externals#7]
Hi,

I am starting to make commits to the ARC module, using the api for the ARC interface. For this, we would need the following libraries available on the DIRAC servers

nordugrid-arc
nordugrid-arc
nordugrid-arc-client
nordugrid-arc-plugins-globus
nordugrid-arc-plugins-needed

The current version of these libraries is 5.0.0-2. I note here, that these libraries are needed only for VO-s which need to submit to sites running the ARC CE (like LHCb).

Thanks and Cheers,
Raja.

**Comment by rajanandakumar** [comment]
Is this task still relevant, if the library will be available in the lcg bindings package?

**Comment by atsareg** [comment]
Yes, this should come with the lcg bindings, not the DIRAC externals
